# -*- coding: utf-8 -*-
"""1-sb-linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqAD_yCJMvpqtnScdWXcl9aafN7UT4U5
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df =  pd.read_csv('homeprices.csv')
df

plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='*')

area_df = df.drop('price',axis='columns')
area_df

price = df.price
price



# Create linear regression object
reg = linear_model.LinearRegression()
reg.fit(area_df,price)
reg.score(area_df,price)

plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='*')
plt.plot(area_df,reg.predict(area_df),color='blue')

reg.predict([[3200]])